### PR TITLE
Fix the case for regex when the line could end with the line-break.

### PR DESCRIPTION
**Pull request by iArtorias**

### CODE REVIEW

**Comment by X-rays5** [comment]
@iArtorias Is it possible to add a test case for this issue?

**Comment by iArtorias** [comment]
Sure, just try adding \r to the end of the string. E.g.:
const std::string str = "test = test1\r";
If 100% fixes the case for the Linux-based systems.

**Comment by X-rays5** [comment]
So I've modified 'Section 1' in the test file for the test to:
```
"[Section 1]\n"
 "; comment\n"
 "# comment2\n"
"test_line_break = test1\r"
"Option 1 = value 1                     ; option 'Option 1' has value 'value 1'\n"
"Option 2 =  value 2                     # option 'Option 2' has value 'value 2'\n"
"oPtion 1    =  value 2\\ \\ \\          ; option 'oPtion 1' has value ' value 2   ', 'oPtion 1' and 'Option 1' are different\n"
"\n"
```

Makes the check for  test_line_break succesfull with this call: `EXPECT_STREQ(section["test_line_break"].as<const char*>(), "test1");`

It fails to parse 'Option 1' after that and outputs `C++ exception with description "Section does not have a value with the key: Option 1" thrown in the test body.`

**Comment by iArtorias** [comment]
The interesting part is that it breaks on the same spot for me with your example, even with an older regex pattern. I will experiment with the patterns and let you know.

**Comment by iArtorias** [comment]
@X-rays5 fixed for good now, I think. Please, check it out  :)

**Comment by X-rays5** [comment]
Lmao can happen. Glad to see it finally working will merge thank you.

**Pull request merged**
